<?

namespace backend\controllers\develop;

use backend\controllers\common\CRUDController;
use common\models\material\Field;
use common\models\material\search\Field as FieldSearch;
use yii\web\NotFoundHttpException;

class FieldController extends CRUDController
{
    public function init()
    {
        $this->mainClass = Field::className();
        $this->searchClass = FieldSearch::className();
        $this->parentController = '/develop/group';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     * @throws NotFoundHttpException
     */
    public function actionIndex($parent = 0)
    {
        throw new NotFoundHttpException();
    }

    /**
     * {@inheritdoc}
     */
    protected function submitSaveClose($model)
    {
        return $this->redirect([$this->parentController . '/update', 'id' => $model->parent->id, 'tab' => 'sub-field']);
    }

    /**
     * {@inheritdoc}
     */
    protected function submitSaveCreate($model)
    {
        $this->redirect(['create', 'parent' => $model->parent->id]);
    }

    /**
     * {@inheritdoc}
     */
    protected function submitSaveCopy($model)
    {
        $this->redirect(['create', 'parent' => $model->parent->id, 'copy' => $model->id]);
    }
}
