<?

namespace backend\controllers\develop;

use backend\controllers\common\CRUDController;
use common\models\material\Group;
use common\models\material\search\Group as GroupSearch;

class GroupController extends CRUDController
{
    public function init()
    {
        $this->mainClass = Group::className();
        $this->searchClass = GroupSearch::className();
        $this->parentController = '/develop/group';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    protected function submitSaveClose($model)
    {
        if ($model->group_id) {
            return $this->redirect([$this->parentController . '/update', 'id' => $model->parent->id, 'tab' => 'sub-group']);
        }
        return parent::submitSaveClose($model);
    }

    /**
     * {@inheritdoc}
     */
    protected function submitSaveCreate($model)
    {
        $this->redirect(['create', 'parent' => $model->parent->id]);
    }

    /**
     * {@inheritdoc}
     */
    protected function submitSaveCopy($model)
    {
        $this->redirect(['create', 'parent' => $model->parent->id, 'copy' => $model->id]);
    }
}
