<?php

namespace common\models\setting;

use common\models\material\Group;
use yii\base\Model;

/**
 * @property string $title
 * @property string $description
 */
class Base extends Model
{
    public $title;
    public $description;

    public function init()
    {
        $material = Group::findOne(4)->material;
        $this->title = $material->title;
        $this->description = $material->getValue(9);
        parent::init(); // TODO: Change the autogenerated stub
    }
}
